### ISSUE TITLE
custom location for freebsd-update-pub.ssl

### ISSUE THREAD

**Issue by geeseven** [mkhon/zabbix-freebsd-release#1]
Greetings,

I am using this script outside of Zabbix and did not want to create the `var/db/zabbix/` folder.  I did not want to hard code a location so I am using the following:

```diff
3c3,8
< PUB_SSL="/var/db/zabbix/freebsd-update-pub.ssl"
---
> if [ -z "$1" ] ; then
>       PUB_SSL="/var/db/zabbix/freebsd-update-pub.ssl"
> else
>       PUB_SSL="$1/freebsd-update-pub.ssl"
> fi
```

Feel free to use this if you like. 

On a different note, I am curious on your thoughts on the [new][0] `freebsd-update updatesready` option.  Personally, I still like your approach as it does not require root access.  

[0]: https://reviews.freebsd.org/D21473

**Comment by mkhon** [comment]
I added the ability to specify FREEBSD_UPDATE_PUB_SSL env var
